version: '3'

services:
  web:
    build:
      context: .
      args:
        - XDEBUG_ENABLE=${XDEBUG_ENABLE}
    container_name: projet-3-oc-web
    image: projet-3-oc-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: projet-oc-3-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/db_data:/var/lib/mysql

volumes:
  db_data: